version: "3"
services:
  skrm_main_api:
    build:
      context: .
      dockerfile: Dockerfile
    command: pm2-docker process.json
    container_name: "skrm_main_api"
    env_file: .env
    ports:
      - 3001:80
    volumes:
      - .:/App
      - /App/node_modules
    networks:
      - localnet
    restart: always
networks:
  localnet:
    external: true
